services:
  redis:
    image: redis
    ports:
      - 6379:6379
    entrypoint: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    labels:
      - com.packtpub.compose.app=task-manager
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - redis-data:/data
      - backup:/backup
  gorest:
    build:
      context: .
      labels:
        - com.packtpub.compose.app=task-manager
    image: task-manager:0.1
    ports:
      - 8080:8080
    environment:
      - REDIS_HOST=redis:6379
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/ping"]
      interval: 20s
      timeout: 10s
      retries: 5
      start_period: 5s
    depends_on:
      - redis
  redis-backup:
    image: bash
    entrypoint: ["bash","snapshot-backup.sh"]
    depends_on:
      - redis
    environment:
      - BACKUP_PERIOD=10
    volumes:
      - ./snapshot-backup.sh:/snapshot-backup.sh
      - redis-data:/data:ro
      - backup:/backup

volumes:
  redis-data:
    labels:
      - com.packtpub.compose.app=task-manager
  backup:
    labels:
      - com.packtpub.compose.app=task-manager